### ISSUE TITLE
ビルド環境のテスト

### ISSUE THREAD

**Issue by ynunokawa** [EsriJapan/arcgis-dev-resources#6]
以下のフローを実施してください。

1. `git clone https://github.com/EsriJapan/arcgis-dev-resources.git` OR 自身のアカウントに Fork 後 `git clone https://github.com/<YOU>/arcgis-dev-resources.git`
- `cd arcgis-dev-resources`
- `git branch build-test`
- `git checkout build-test`
- `npm i`
- `npm build`
- `npm test`
- 自動的にブラウザーが起動してページ (`http://127.0.0.1:5000/`) が開くので確認してください

これが通ればページの更新作業が可能です。
[Node.js/npm](https://nodejs.org/en/) 入れていない方はインストールしてください。

**Comment by yozaw** [comment]
ページ開くのを確認しました。

**Comment by ynunokawa** [comment]
@yozaw thx!

**Comment by ej-asuzuki** [comment]
LGTM

**Comment by horui** [comment]
開けた。ゴマ。

**Comment by wakanasato** [comment]
開けました☆
